### ISSUE TITLE
Cargo Weights & Fuel Tanks

### ISSUE THREAD

**Issue by ghost** [FGMEMBERS/A330-200#3]
In this [EASA Type Certificate from 2015](https://easa.europa.eu/system/files/dfu/TCDS_EASA%20A%20004_A330_Iss_43_21092015.pdf) I found some different weights for the Cargo Compartment of the A330-200 (see page 30).

Max. Forward Cargo: 18.869kg / 41.600lbs
Max. Aft Cargo: 15.241kg / 33.600lbs
Max. Rear (Bulk) Cargo: 3.468kg / 7.646lbs

This one would be easy to adjust, but I think, that the Fuel System would also need a makeover. What I can see from the Type Certificate and the [Flight Crew Operating Manual](http://www.smartcockpit.com/aircraft-ressources/A330-Fuel.html) from Smartcockpit the A330-200 has 6 Tanks: 2 Outer Tanks, 2 Inner Tanks, 1 Center Tank and 1 Trim Tank in the Elevator Wings. The 4 Vent Tanks it has are only used for maintenance purpose and are not during flight.

Outer Wing (each): 2.948kg (unusable: 11kg)
Inner Wing (each): 33.920kg (unusable: 129kg)
Center: 33.565kg (unusable: 67kg)
Trim: 5.032kg (unusable: 5kg)
Density: 0,8076301kg/liter [JSBSim Fuel Densities](http://wiki.flightgear.org/JSBSim_Fuel_System#Fuel_Densities_.28lb.2Fgallon.29:)

Also I think the "Fuel Pipes" are not necessary, the engines can be fed directly from the inner tanks.

**Comment by FGDATA** [comment]
> > This one would be easy to adjust, but I think, that the Fuel System would also need a makeover. 

I would say, if you get a patch, bring it on :+1: 

@IAHM-COL @FGMEMBERS/omega

**Comment by ghost** [comment]
Sure, I just wanted to ask first if you think, this makes sense.

**Comment by FGDATA** [comment]
Sounds very reasonable to me
Feel free to adjust, then fly it to see how it feels to you, if you are happy with the behavior, feel free to share your code ;)

**Comment by jan-hudec** [comment]
> Also I think the "Fuel Pipes" are not necessary, the engines can be fed directly from the inner tanks.

They are not strictly necessary, but they separate the simplistic JSBSim fuel logic from the fuel system implemented in Nasal, so I think they should stay there. Otherwise, go ahead.

**Comment by ghost** [comment]
Sorry for taking so long, but I didn't had so much time to work on the new fuel system. Finally I finished it and uploaded the commit on my A330-200 fork.

Would be nice if someone could check it out and give me feedback.
